### PR TITLE
Basic Driving Auto

### PR DESCRIPTION
**Pull request by dltompki**
Working on #10 and #15 

New Commands:
- DriveEncoder (auto drive a certain number of wheel rotations)
- DriveInches (wrapper of DriveEncoder for inches)
- DriveCM (wrapper of DriveEncoder for centimeters)
- OnePowerCell (combines DriveInches with activating and deactivating intake mode in a SequentialCommandGroup)

Also:
- Added some constants

Please do not merge until we have tested on the robot

### CODE REVIEW

**Review by jefft138 — COMMENTED** [review]
My understanding of the getRightEncPos call in the DriveTrainC class is that it will return the number of rotations of the motor, which doesn't match the number of rotations of the wheel since there is a gearbox between the motor and the wheel. We need to divide these rotations by the gear ratio in the gearbox to get the wheel rotations. I think this complexity can be maintained in DriveEncoder such that the interface to DriveEncoder can be based on wheel rotations and this can then be multiplied by the gear ratio to get motor rotations (or divide the encoder position by this ratio to compare wheel rotations).

To test our logic, we can use DriveTimed command which will print out starting encoder value and ending encoder value after driving a fixed amount of time, then measure how far the robot drove and compare that with expected encoder values.

Regarding getAxisForward, yes up is negative. This is not a wiring issue.

**Comment by dltompki** [comment]
@jefft138 Okay, we'll have to ask mechanical what the gear ratio is. Your testing methodology makes sense, although I'm not too familiar with DriveTimed.

I'll remove my comment since the implementation is correct. Just wanted to make sure.

**Review by jefft138 — APPROVED** [review]
RobotContainer 
- Multiple imports of SmartDashboard added, lines 11 & 16.

DriveEncoder
- We can probably remove some of the printouts. We only have 1 or 2 that will come out each time the command runs, so I'm OK if we want to leave them for other commands that will build on this base command.
- Even though m_driveSpeed is not needed when m_motorRotations == 0, it is good practice to make sure member variables are all initialized. We should set it to 0 here.

OnePowerCell
- How did the robot do picking up the ball while driving at our autonomous speed? I'm assuming that the intake still worked fine, but we might want to test speeding up the robot and see if there is a speed at which the ball starts jamming if we are picking it up at full auto speed. 
- I know this doesn't apply to this command, but later when we try to turn after picking up the ball, we will also want to see that turning with the ball still in the rollers toward the intake doesn't cause the ball to jam

I am approving these changes and any changes you want to make from the above we can do on the next branch, or you can choose to make these updates before merging back to master.

**Comment by dltompki** [comment]
Full details of changes I made after PR approval can be viewed in the comments for 4c84b628b1fc6d6f0aea0845afc3ae7f9d1c7a06.

> How did the robot do picking up the ball while driving at our autonomous speed?

All systems worked as well as they do in teleop. Picking up the ball did not seem to affect distance consistency either.
> later when we try to turn after picking up the ball, we will also want to see that turning with the ball still in the rollers toward the intake doesn't cause the ball to jam

Added this to #11 

This PR is ready for merge except that we did not test driving backward in autonomous. We will need to quickly test this on Wednesday.

**Pull request merged**
